/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteImport } from './routes/user'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as UserDashboardRouteImport } from './routes/user/dashboard'
import { Route as UserSlugRouteImport } from './routes/user/$slug'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminRolesRouteImport } from './routes/admin/roles'
import { Route as AdminSlugRouteImport } from './routes/admin/$slug'
import { Route as UserModulesHrTasksRouteImport } from './routes/user/modules/hr/tasks'
import { Route as UserModulesHrSupportRouteImport } from './routes/user/modules/hr/support'
import { Route as UserModulesHrSettingsRouteImport } from './routes/user/modules/hr/settings'
import { Route as UserModulesHrPersonalRouteImport } from './routes/user/modules/hr/personal'
import { Route as UserModulesHrPerformanceRouteImport } from './routes/user/modules/hr/performance'
import { Route as UserModulesHrPeopleRouteImport } from './routes/user/modules/hr/people'
import { Route as UserModulesHrPayslipRouteImport } from './routes/user/modules/hr/payslip'
import { Route as UserModulesHrJobReferenceRouteImport } from './routes/user/modules/hr/job-reference'
import { Route as UserModulesHrDocumentsRouteImport } from './routes/user/modules/hr/documents'
import { Route as UserModulesHrBenefitsRouteImport } from './routes/user/modules/hr/benefits'
import { Route as UserModulesHrAttendanceRouteImport } from './routes/user/modules/hr/attendance'

const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const UserDashboardRoute = UserDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => UserRoute,
} as any)
const UserSlugRoute = UserSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => UserRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSlugRoute = AdminSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AdminRoute,
} as any)
const UserModulesHrTasksRoute = UserModulesHrTasksRouteImport.update({
  id: '/modules/hr/tasks',
  path: '/modules/hr/tasks',
  getParentRoute: () => UserRoute,
} as any)
const UserModulesHrSupportRoute = UserModulesHrSupportRouteImport.update({
  id: '/modules/hr/support',
  path: '/modules/hr/support',
  getParentRoute: () => UserRoute,
} as any)
const UserModulesHrSettingsRoute = UserModulesHrSettingsRouteImport.update({
  id: '/modules/hr/settings',
  path: '/modules/hr/settings',
  getParentRoute: () => UserRoute,
} as any)
const UserModulesHrPersonalRoute = UserModulesHrPersonalRouteImport.update({
  id: '/modules/hr/personal',
  path: '/modules/hr/personal',
  getParentRoute: () => UserRoute,
} as any)
const UserModulesHrPerformanceRoute =
  UserModulesHrPerformanceRouteImport.update({
    id: '/modules/hr/performance',
    path: '/modules/hr/performance',
    getParentRoute: () => UserRoute,
  } as any)
const UserModulesHrPeopleRoute = UserModulesHrPeopleRouteImport.update({
  id: '/modules/hr/people',
  path: '/modules/hr/people',
  getParentRoute: () => UserRoute,
} as any)
const UserModulesHrPayslipRoute = UserModulesHrPayslipRouteImport.update({
  id: '/modules/hr/payslip',
  path: '/modules/hr/payslip',
  getParentRoute: () => UserRoute,
} as any)
const UserModulesHrJobReferenceRoute =
  UserModulesHrJobReferenceRouteImport.update({
    id: '/modules/hr/job-reference',
    path: '/modules/hr/job-reference',
    getParentRoute: () => UserRoute,
  } as any)
const UserModulesHrDocumentsRoute = UserModulesHrDocumentsRouteImport.update({
  id: '/modules/hr/documents',
  path: '/modules/hr/documents',
  getParentRoute: () => UserRoute,
} as any)
const UserModulesHrBenefitsRoute = UserModulesHrBenefitsRouteImport.update({
  id: '/modules/hr/benefits',
  path: '/modules/hr/benefits',
  getParentRoute: () => UserRoute,
} as any)
const UserModulesHrAttendanceRoute = UserModulesHrAttendanceRouteImport.update({
  id: '/modules/hr/attendance',
  path: '/modules/hr/attendance',
  getParentRoute: () => UserRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/profile': typeof ProfileRoute
  '/user': typeof UserRouteWithChildren
  '/admin/$slug': typeof AdminSlugRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/user/$slug': typeof UserSlugRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/admin/': typeof AdminIndexRoute
  '/user/modules/hr/attendance': typeof UserModulesHrAttendanceRoute
  '/user/modules/hr/benefits': typeof UserModulesHrBenefitsRoute
  '/user/modules/hr/documents': typeof UserModulesHrDocumentsRoute
  '/user/modules/hr/job-reference': typeof UserModulesHrJobReferenceRoute
  '/user/modules/hr/payslip': typeof UserModulesHrPayslipRoute
  '/user/modules/hr/people': typeof UserModulesHrPeopleRoute
  '/user/modules/hr/performance': typeof UserModulesHrPerformanceRoute
  '/user/modules/hr/personal': typeof UserModulesHrPersonalRoute
  '/user/modules/hr/settings': typeof UserModulesHrSettingsRoute
  '/user/modules/hr/support': typeof UserModulesHrSupportRoute
  '/user/modules/hr/tasks': typeof UserModulesHrTasksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/profile': typeof ProfileRoute
  '/user': typeof UserRouteWithChildren
  '/admin/$slug': typeof AdminSlugRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/user/$slug': typeof UserSlugRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/admin': typeof AdminIndexRoute
  '/user/modules/hr/attendance': typeof UserModulesHrAttendanceRoute
  '/user/modules/hr/benefits': typeof UserModulesHrBenefitsRoute
  '/user/modules/hr/documents': typeof UserModulesHrDocumentsRoute
  '/user/modules/hr/job-reference': typeof UserModulesHrJobReferenceRoute
  '/user/modules/hr/payslip': typeof UserModulesHrPayslipRoute
  '/user/modules/hr/people': typeof UserModulesHrPeopleRoute
  '/user/modules/hr/performance': typeof UserModulesHrPerformanceRoute
  '/user/modules/hr/personal': typeof UserModulesHrPersonalRoute
  '/user/modules/hr/settings': typeof UserModulesHrSettingsRoute
  '/user/modules/hr/support': typeof UserModulesHrSupportRoute
  '/user/modules/hr/tasks': typeof UserModulesHrTasksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/profile': typeof ProfileRoute
  '/user': typeof UserRouteWithChildren
  '/admin/$slug': typeof AdminSlugRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/user/$slug': typeof UserSlugRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/admin/': typeof AdminIndexRoute
  '/user/modules/hr/attendance': typeof UserModulesHrAttendanceRoute
  '/user/modules/hr/benefits': typeof UserModulesHrBenefitsRoute
  '/user/modules/hr/documents': typeof UserModulesHrDocumentsRoute
  '/user/modules/hr/job-reference': typeof UserModulesHrJobReferenceRoute
  '/user/modules/hr/payslip': typeof UserModulesHrPayslipRoute
  '/user/modules/hr/people': typeof UserModulesHrPeopleRoute
  '/user/modules/hr/performance': typeof UserModulesHrPerformanceRoute
  '/user/modules/hr/personal': typeof UserModulesHrPersonalRoute
  '/user/modules/hr/settings': typeof UserModulesHrSettingsRoute
  '/user/modules/hr/support': typeof UserModulesHrSupportRoute
  '/user/modules/hr/tasks': typeof UserModulesHrTasksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/profile'
    | '/user'
    | '/admin/$slug'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/users'
    | '/user/$slug'
    | '/user/dashboard'
    | '/admin/'
    | '/user/modules/hr/attendance'
    | '/user/modules/hr/benefits'
    | '/user/modules/hr/documents'
    | '/user/modules/hr/job-reference'
    | '/user/modules/hr/payslip'
    | '/user/modules/hr/people'
    | '/user/modules/hr/performance'
    | '/user/modules/hr/personal'
    | '/user/modules/hr/settings'
    | '/user/modules/hr/support'
    | '/user/modules/hr/tasks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/profile'
    | '/user'
    | '/admin/$slug'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/users'
    | '/user/$slug'
    | '/user/dashboard'
    | '/admin'
    | '/user/modules/hr/attendance'
    | '/user/modules/hr/benefits'
    | '/user/modules/hr/documents'
    | '/user/modules/hr/job-reference'
    | '/user/modules/hr/payslip'
    | '/user/modules/hr/people'
    | '/user/modules/hr/performance'
    | '/user/modules/hr/personal'
    | '/user/modules/hr/settings'
    | '/user/modules/hr/support'
    | '/user/modules/hr/tasks'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/profile'
    | '/user'
    | '/admin/$slug'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/users'
    | '/user/$slug'
    | '/user/dashboard'
    | '/admin/'
    | '/user/modules/hr/attendance'
    | '/user/modules/hr/benefits'
    | '/user/modules/hr/documents'
    | '/user/modules/hr/job-reference'
    | '/user/modules/hr/payslip'
    | '/user/modules/hr/people'
    | '/user/modules/hr/performance'
    | '/user/modules/hr/personal'
    | '/user/modules/hr/settings'
    | '/user/modules/hr/support'
    | '/user/modules/hr/tasks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ProfileRoute: typeof ProfileRoute
  UserRoute: typeof UserRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/user/dashboard': {
      id: '/user/dashboard'
      path: '/dashboard'
      fullPath: '/user/dashboard'
      preLoaderRoute: typeof UserDashboardRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/$slug': {
      id: '/user/$slug'
      path: '/$slug'
      fullPath: '/user/$slug'
      preLoaderRoute: typeof UserSlugRouteImport
      parentRoute: typeof UserRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/$slug': {
      id: '/admin/$slug'
      path: '/$slug'
      fullPath: '/admin/$slug'
      preLoaderRoute: typeof AdminSlugRouteImport
      parentRoute: typeof AdminRoute
    }
    '/user/modules/hr/tasks': {
      id: '/user/modules/hr/tasks'
      path: '/modules/hr/tasks'
      fullPath: '/user/modules/hr/tasks'
      preLoaderRoute: typeof UserModulesHrTasksRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/modules/hr/support': {
      id: '/user/modules/hr/support'
      path: '/modules/hr/support'
      fullPath: '/user/modules/hr/support'
      preLoaderRoute: typeof UserModulesHrSupportRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/modules/hr/settings': {
      id: '/user/modules/hr/settings'
      path: '/modules/hr/settings'
      fullPath: '/user/modules/hr/settings'
      preLoaderRoute: typeof UserModulesHrSettingsRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/modules/hr/personal': {
      id: '/user/modules/hr/personal'
      path: '/modules/hr/personal'
      fullPath: '/user/modules/hr/personal'
      preLoaderRoute: typeof UserModulesHrPersonalRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/modules/hr/performance': {
      id: '/user/modules/hr/performance'
      path: '/modules/hr/performance'
      fullPath: '/user/modules/hr/performance'
      preLoaderRoute: typeof UserModulesHrPerformanceRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/modules/hr/people': {
      id: '/user/modules/hr/people'
      path: '/modules/hr/people'
      fullPath: '/user/modules/hr/people'
      preLoaderRoute: typeof UserModulesHrPeopleRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/modules/hr/payslip': {
      id: '/user/modules/hr/payslip'
      path: '/modules/hr/payslip'
      fullPath: '/user/modules/hr/payslip'
      preLoaderRoute: typeof UserModulesHrPayslipRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/modules/hr/job-reference': {
      id: '/user/modules/hr/job-reference'
      path: '/modules/hr/job-reference'
      fullPath: '/user/modules/hr/job-reference'
      preLoaderRoute: typeof UserModulesHrJobReferenceRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/modules/hr/documents': {
      id: '/user/modules/hr/documents'
      path: '/modules/hr/documents'
      fullPath: '/user/modules/hr/documents'
      preLoaderRoute: typeof UserModulesHrDocumentsRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/modules/hr/benefits': {
      id: '/user/modules/hr/benefits'
      path: '/modules/hr/benefits'
      fullPath: '/user/modules/hr/benefits'
      preLoaderRoute: typeof UserModulesHrBenefitsRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/modules/hr/attendance': {
      id: '/user/modules/hr/attendance'
      path: '/modules/hr/attendance'
      fullPath: '/user/modules/hr/attendance'
      preLoaderRoute: typeof UserModulesHrAttendanceRouteImport
      parentRoute: typeof UserRoute
    }
  }
}

interface AdminRouteChildren {
  AdminSlugRoute: typeof AdminSlugRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSlugRoute: AdminSlugRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface UserRouteChildren {
  UserSlugRoute: typeof UserSlugRoute
  UserDashboardRoute: typeof UserDashboardRoute
  UserModulesHrAttendanceRoute: typeof UserModulesHrAttendanceRoute
  UserModulesHrBenefitsRoute: typeof UserModulesHrBenefitsRoute
  UserModulesHrDocumentsRoute: typeof UserModulesHrDocumentsRoute
  UserModulesHrJobReferenceRoute: typeof UserModulesHrJobReferenceRoute
  UserModulesHrPayslipRoute: typeof UserModulesHrPayslipRoute
  UserModulesHrPeopleRoute: typeof UserModulesHrPeopleRoute
  UserModulesHrPerformanceRoute: typeof UserModulesHrPerformanceRoute
  UserModulesHrPersonalRoute: typeof UserModulesHrPersonalRoute
  UserModulesHrSettingsRoute: typeof UserModulesHrSettingsRoute
  UserModulesHrSupportRoute: typeof UserModulesHrSupportRoute
  UserModulesHrTasksRoute: typeof UserModulesHrTasksRoute
}

const UserRouteChildren: UserRouteChildren = {
  UserSlugRoute: UserSlugRoute,
  UserDashboardRoute: UserDashboardRoute,
  UserModulesHrAttendanceRoute: UserModulesHrAttendanceRoute,
  UserModulesHrBenefitsRoute: UserModulesHrBenefitsRoute,
  UserModulesHrDocumentsRoute: UserModulesHrDocumentsRoute,
  UserModulesHrJobReferenceRoute: UserModulesHrJobReferenceRoute,
  UserModulesHrPayslipRoute: UserModulesHrPayslipRoute,
  UserModulesHrPeopleRoute: UserModulesHrPeopleRoute,
  UserModulesHrPerformanceRoute: UserModulesHrPerformanceRoute,
  UserModulesHrPersonalRoute: UserModulesHrPersonalRoute,
  UserModulesHrSettingsRoute: UserModulesHrSettingsRoute,
  UserModulesHrSupportRoute: UserModulesHrSupportRoute,
  UserModulesHrTasksRoute: UserModulesHrTasksRoute,
}

const UserRouteWithChildren = UserRoute._addFileChildren(UserRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ProfileRoute: ProfileRoute,
  UserRoute: UserRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
