/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteImport } from './routes/user'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as UserTasksRouteImport } from './routes/user/tasks'
import { Route as UserSupportRouteImport } from './routes/user/support'
import { Route as UserSettingsRouteImport } from './routes/user/settings'
import { Route as UserPersonalRouteImport } from './routes/user/personal'
import { Route as UserPerformanceRouteImport } from './routes/user/performance'
import { Route as UserPeopleRouteImport } from './routes/user/people'
import { Route as UserPayslipRouteImport } from './routes/user/payslip'
import { Route as UserJobReferenceRouteImport } from './routes/user/job-reference'
import { Route as UserDocumentsRouteImport } from './routes/user/documents'
import { Route as UserDashboardRouteImport } from './routes/user/dashboard'
import { Route as UserBenefitsRouteImport } from './routes/user/benefits'
import { Route as UserAttendanceRouteImport } from './routes/user/attendance'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminRolesRouteImport } from './routes/admin/roles'

const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const UserTasksRoute = UserTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => UserRoute,
} as any)
const UserSupportRoute = UserSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => UserRoute,
} as any)
const UserSettingsRoute = UserSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => UserRoute,
} as any)
const UserPersonalRoute = UserPersonalRouteImport.update({
  id: '/personal',
  path: '/personal',
  getParentRoute: () => UserRoute,
} as any)
const UserPerformanceRoute = UserPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => UserRoute,
} as any)
const UserPeopleRoute = UserPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => UserRoute,
} as any)
const UserPayslipRoute = UserPayslipRouteImport.update({
  id: '/payslip',
  path: '/payslip',
  getParentRoute: () => UserRoute,
} as any)
const UserJobReferenceRoute = UserJobReferenceRouteImport.update({
  id: '/job-reference',
  path: '/job-reference',
  getParentRoute: () => UserRoute,
} as any)
const UserDocumentsRoute = UserDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => UserRoute,
} as any)
const UserDashboardRoute = UserDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => UserRoute,
} as any)
const UserBenefitsRoute = UserBenefitsRouteImport.update({
  id: '/benefits',
  path: '/benefits',
  getParentRoute: () => UserRoute,
} as any)
const UserAttendanceRoute = UserAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => UserRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/profile': typeof ProfileRoute
  '/user': typeof UserRouteWithChildren
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/user/attendance': typeof UserAttendanceRoute
  '/user/benefits': typeof UserBenefitsRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/user/documents': typeof UserDocumentsRoute
  '/user/job-reference': typeof UserJobReferenceRoute
  '/user/payslip': typeof UserPayslipRoute
  '/user/people': typeof UserPeopleRoute
  '/user/performance': typeof UserPerformanceRoute
  '/user/personal': typeof UserPersonalRoute
  '/user/settings': typeof UserSettingsRoute
  '/user/support': typeof UserSupportRoute
  '/user/tasks': typeof UserTasksRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/profile': typeof ProfileRoute
  '/user': typeof UserRouteWithChildren
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/user/attendance': typeof UserAttendanceRoute
  '/user/benefits': typeof UserBenefitsRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/user/documents': typeof UserDocumentsRoute
  '/user/job-reference': typeof UserJobReferenceRoute
  '/user/payslip': typeof UserPayslipRoute
  '/user/people': typeof UserPeopleRoute
  '/user/performance': typeof UserPerformanceRoute
  '/user/personal': typeof UserPersonalRoute
  '/user/settings': typeof UserSettingsRoute
  '/user/support': typeof UserSupportRoute
  '/user/tasks': typeof UserTasksRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/profile': typeof ProfileRoute
  '/user': typeof UserRouteWithChildren
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/user/attendance': typeof UserAttendanceRoute
  '/user/benefits': typeof UserBenefitsRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/user/documents': typeof UserDocumentsRoute
  '/user/job-reference': typeof UserJobReferenceRoute
  '/user/payslip': typeof UserPayslipRoute
  '/user/people': typeof UserPeopleRoute
  '/user/performance': typeof UserPerformanceRoute
  '/user/personal': typeof UserPersonalRoute
  '/user/settings': typeof UserSettingsRoute
  '/user/support': typeof UserSupportRoute
  '/user/tasks': typeof UserTasksRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/profile'
    | '/user'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/users'
    | '/user/attendance'
    | '/user/benefits'
    | '/user/dashboard'
    | '/user/documents'
    | '/user/job-reference'
    | '/user/payslip'
    | '/user/people'
    | '/user/performance'
    | '/user/personal'
    | '/user/settings'
    | '/user/support'
    | '/user/tasks'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/profile'
    | '/user'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/users'
    | '/user/attendance'
    | '/user/benefits'
    | '/user/dashboard'
    | '/user/documents'
    | '/user/job-reference'
    | '/user/payslip'
    | '/user/people'
    | '/user/performance'
    | '/user/personal'
    | '/user/settings'
    | '/user/support'
    | '/user/tasks'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/profile'
    | '/user'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/users'
    | '/user/attendance'
    | '/user/benefits'
    | '/user/dashboard'
    | '/user/documents'
    | '/user/job-reference'
    | '/user/payslip'
    | '/user/people'
    | '/user/performance'
    | '/user/personal'
    | '/user/settings'
    | '/user/support'
    | '/user/tasks'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ProfileRoute: typeof ProfileRoute
  UserRoute: typeof UserRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/user/tasks': {
      id: '/user/tasks'
      path: '/tasks'
      fullPath: '/user/tasks'
      preLoaderRoute: typeof UserTasksRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/support': {
      id: '/user/support'
      path: '/support'
      fullPath: '/user/support'
      preLoaderRoute: typeof UserSupportRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/settings': {
      id: '/user/settings'
      path: '/settings'
      fullPath: '/user/settings'
      preLoaderRoute: typeof UserSettingsRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/personal': {
      id: '/user/personal'
      path: '/personal'
      fullPath: '/user/personal'
      preLoaderRoute: typeof UserPersonalRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/performance': {
      id: '/user/performance'
      path: '/performance'
      fullPath: '/user/performance'
      preLoaderRoute: typeof UserPerformanceRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/people': {
      id: '/user/people'
      path: '/people'
      fullPath: '/user/people'
      preLoaderRoute: typeof UserPeopleRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/payslip': {
      id: '/user/payslip'
      path: '/payslip'
      fullPath: '/user/payslip'
      preLoaderRoute: typeof UserPayslipRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/job-reference': {
      id: '/user/job-reference'
      path: '/job-reference'
      fullPath: '/user/job-reference'
      preLoaderRoute: typeof UserJobReferenceRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/documents': {
      id: '/user/documents'
      path: '/documents'
      fullPath: '/user/documents'
      preLoaderRoute: typeof UserDocumentsRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/dashboard': {
      id: '/user/dashboard'
      path: '/dashboard'
      fullPath: '/user/dashboard'
      preLoaderRoute: typeof UserDashboardRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/benefits': {
      id: '/user/benefits'
      path: '/benefits'
      fullPath: '/user/benefits'
      preLoaderRoute: typeof UserBenefitsRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/attendance': {
      id: '/user/attendance'
      path: '/attendance'
      fullPath: '/user/attendance'
      preLoaderRoute: typeof UserAttendanceRouteImport
      parentRoute: typeof UserRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminRolesRoute: AdminRolesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface UserRouteChildren {
  UserAttendanceRoute: typeof UserAttendanceRoute
  UserBenefitsRoute: typeof UserBenefitsRoute
  UserDashboardRoute: typeof UserDashboardRoute
  UserDocumentsRoute: typeof UserDocumentsRoute
  UserJobReferenceRoute: typeof UserJobReferenceRoute
  UserPayslipRoute: typeof UserPayslipRoute
  UserPeopleRoute: typeof UserPeopleRoute
  UserPerformanceRoute: typeof UserPerformanceRoute
  UserPersonalRoute: typeof UserPersonalRoute
  UserSettingsRoute: typeof UserSettingsRoute
  UserSupportRoute: typeof UserSupportRoute
  UserTasksRoute: typeof UserTasksRoute
}

const UserRouteChildren: UserRouteChildren = {
  UserAttendanceRoute: UserAttendanceRoute,
  UserBenefitsRoute: UserBenefitsRoute,
  UserDashboardRoute: UserDashboardRoute,
  UserDocumentsRoute: UserDocumentsRoute,
  UserJobReferenceRoute: UserJobReferenceRoute,
  UserPayslipRoute: UserPayslipRoute,
  UserPeopleRoute: UserPeopleRoute,
  UserPerformanceRoute: UserPerformanceRoute,
  UserPersonalRoute: UserPersonalRoute,
  UserSettingsRoute: UserSettingsRoute,
  UserSupportRoute: UserSupportRoute,
  UserTasksRoute: UserTasksRoute,
}

const UserRouteWithChildren = UserRoute._addFileChildren(UserRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ProfileRoute: ProfileRoute,
  UserRoute: UserRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
